// The link boundary on the ITINERARY page.
//
// lib/linkify.test.ts already covers this for Ask a Local answers. The
// itinerary page had no equivalent and needed one more, not less: an Ask a
// Local answer is prose the model writes about places, whereas
// `source_urls` is a field the model fills with URLs directly - types.ts
// says so in as many words, "the model writes the real URL(s) it used
// directly into this field" - and the page rendered it as `href={url}` with
// no scheme check at all.
//
// React escapes attribute VALUES, so that is not classic XSS. But a browser
// still executes `href="javascript:..."` when someone clicks it, React does
// not block that scheme, and the brief's free-text fields (interests,
// must_see, hard_no) are traveller-supplied - so a prompt injection aimed
// at that field had a clickable path to script execution.
//
// Run: npm run test:itinerary-links

import { safeHref } from "./linkify";
import { check, finish, heading, section } from "./testutil";

heading("itinerary link boundary");

/** What the page now does with every URL before it becomes an href. */
const linksFrom = (urls: unknown[]): string[] =>
  urls
    .map((u) => (typeof u === "string" ? safeHref(u) : null))
    .filter((h): h is string => h !== null);

async function main() {
  section("schemes that must never reach an href");

  for (const bad of [
    "javascript:alert(1)",
    "JavaScript:alert(1)",
    "  javascript:alert(1)",
    "java\tscript:alert(1)",
    "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
    "vbscript:msgbox(1)",
    "file:///etc/passwd",
    "about:blank",
    "blob:https://example.com/uuid",
    // These are the ones that distinguish the SCHEME check from the
    // hostname check. `javascript:alert(1)` is an opaque URL whose hostname
    // is "" and so is already caught by the dot rule - removing the scheme
    // check entirely left the suite green, which is how this gap was found.
    // Give the scheme an authority with a dot in it and only the scheme
    // check stands between it and an href.
    "javascript://example.com/%0Aalert(1)",
    "javascript://good.example.com/%0D%0Aalert(document.domain)",
    "data://example.com/x",
  ]) {
    check(`rejected: ${JSON.stringify(bad.slice(0, 34))}`, safeHref(bad) === null, String(safeHref(bad)));
  }

  section("real source links still work");

  for (const good of [
    "https://www.timeout.com/rome/restaurants",
    "http://example.com/a?b=c#d",
    "https://en.wikipedia.org/wiki/Colosseum",
  ]) {
    check(`accepted: ${good.slice(0, 40)}`, safeHref(good) !== null, String(safeHref(good)));
  }

  section("the shapes a model actually emits");

  // A bare hostname with no scheme is not a URL; rendering it as an href
  // would make the browser resolve it against our own origin.
  check("a bare hostname is rejected", safeHref("timeout.com/rome") === null);
  check("a hostname with no dot is rejected", safeHref("https://localhost/admin") === null);
  check("an empty string is rejected", safeHref("") === null);
  check("whitespace is rejected", safeHref("   ") === null);
  // "www." is the one forgiving case, and deliberate - see linkify.ts.
  check("www. is upgraded to https", safeHref("www.timeout.com/rome") === "https://www.timeout.com/rome");

  section("the array the page maps over");

  {
    const mixed = linksFrom([
      "https://good.example.com/a",
      "javascript:alert(1)",
      "https://good.example.com/b",
      null,
      42,
      "",
      undefined,
    ]);
    check("only the safe http(s) links survive", mixed.length === 2, JSON.stringify(mixed));
    check("and they keep their order", mixed[0].includes("/a") && mixed[1].includes("/b"), JSON.stringify(mixed));
  }

  {
    // An item whose every source is unsafe must render NO link row at all,
    // rather than an empty anchor or a row of dead links.
    const allBad = linksFrom(["javascript:alert(1)", "data:text/html,x", "about:blank"]);
    check("an all-unsafe list renders nothing", allBad.length === 0, JSON.stringify(allBad));
  }

  check("a missing source_urls is simply empty", linksFrom([]).length === 0);

  section("the two links the worker builds itself");

  // google_maps_url and flight_search_url are built from fixed https
  // templates with encodeURIComponent, so they are safe today. They are run
  // through the same boundary anyway: a job generated by an older build is
  // still in Redis for 30 days, and a future change to either builder
  // should not be able to put an arbitrary scheme into an href.
  check(
    "a real Maps search URL passes",
    safeHref("https://www.google.com/maps/search/?api=1&query=Armando%20al%20Pantheon&query_place_id=places/abc") !== null
  );
  check(
    "a real Google Flights URL passes",
    safeHref("https://www.google.com/travel/flights?q=Sofia%20to%20Rome%202026-04-11") !== null
  );
  check("a venue name with a quote in it does not break the URL", (() => {
    const url = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`Da Enzo "al 29"`)}`;
    const safe = safeHref(url);
    return safe !== null && !safe.includes('"');
  })());

  finish();
}

main();
